In [1]:
import pandas as pd

In [2]:
# Reads in csv files
happiness_data_2015 = pd.read_csv("data/2015.csv")
happiness_data_2016 = pd.read_csv("data/2016.csv")
happiness_data_2017 = pd.read_csv("data/2017.csv")
happiness_data_2018 = pd.read_csv("data/2018.csv")

# View dataframe
happiness_data_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [3]:
# Adds default year values to each DataFrame
happiness_data_2015["Year"] = '2015'
happiness_data_2016["Year"] = '2016'
happiness_data_2017["Year"] = '2017'
happiness_data_2018["Year"] = '2018'

# View dataframe to make sure field "Year" was added in
happiness_data_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015

In [4]:
happiness_data_2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year'],
      dtype='object')

In [5]:
happiness_data_2016.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual', 'Year'],
      dtype='object')

In [6]:
happiness_data_2017.columns
happiness_data_2017= happiness_data_2017.rename(columns={"Happiness.Rank": "Happiness Rank", 
                                    "Happiness.Score": "Happiness Score",
                                   "Economy..GDP.per.Capita.": "Economy (GDP per Capita)",
                                    "Health..Life.Expectancy.": "Health (Life Expectancy)",
                                    "Trust..Government.Corruption.":"Trust (Government Corruption)",
                                    "Dystopia.Residual": "Dystopia Residual"
                                   })
happiness_data_2017.columns

Index(['Country', 'Happiness Rank', 'Happiness Score', 'Whisker.high',
       'Whisker.low', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Generosity',
       'Trust (Government Corruption)', 'Dystopia Residual', 'Year'],
      dtype='object')

In [7]:
happiness_data_2018.columns
happiness_data_2018= happiness_data_2018.rename(columns={"Overall rank": "Happiness Rank",
                                                         "Country or region":"Country",
                                    "Score": "Happiness Score",
                                   "GDP per capita": "Economy (GDP per Capita)",
                                    "Healthy life expectancy": "Health (Life Expectancy)",
                                    "Perceptions of corruption":"Trust (Government Corruption)",
                                    "Dystopia.Residual": "Dystopia Residual",
                                                         "Freedom to make life choices": "Freedom",
                                                         "Social support":"Family"
                                   })
happiness_data_2018.columns

Index(['Happiness Rank', 'Country', 'Happiness Score',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Generosity', 'Trust (Government Corruption)', 'Year'],
      dtype='object')

In [8]:
# Read in file with countries' latitude and longitude coordinates

geo_data = pd.read_csv("data/countries.csv")
geo_data.head()
# geo_data.dtypes

   Unnamed: 0  country_id      country code   Latitude  Longitude
0           0           1  Afghanistan   AF  33.939110  67.709953
1           1           2      Albania   AL  41.153332  20.168331
2           2           3      Algeria   DZ  28.033886   1.659626
3           3           4       Angola   AO -11.202692  17.873887
4           4           5    Argentina   AR -38.416097 -63.616672

In [9]:
geo_data.dtypes

Unnamed: 0      int64
country_id      int64
country        object
code           object
Latitude      float64
Longitude     float64
dtype: object

In [10]:
clean_geo = geo_data.drop(columns=['Unnamed: 0', 'country_id', 'code'])
clean_geo.head()

       country   Latitude  Longitude
0  Afghanistan  33.939110  67.709953
1      Albania  41.153332  20.168331
2      Algeria  28.033886   1.659626
3       Angola -11.202692  17.873887
4    Argentina -38.416097 -63.616672

In [11]:
# Dataframes to load to database
merged_2018 = pd.merge(happiness_data_2018, clean_geo, left_on='Country', right_on='country', how='inner')
merged_2017 = pd.merge(happiness_data_2017, clean_geo, left_on='Country', right_on='country', how='inner')
merged_2016 = pd.merge(happiness_data_2016, clean_geo, left_on='Country', right_on='country', how='inner')
merged_2015 = pd.merge(happiness_data_2015, clean_geo, left_on='Country', right_on='country', how='inner')

In [12]:
merged_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,country,Latitude,Longitude
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,Switzerland,46.818188,8.227512
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,Iceland,64.963051,-19.020835
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,Denmark,56.263920,9.501785
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,Norway,60.472024,8.468946
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,Canada,56.130366,-106.346771

In [13]:
# Combined all dataframes to verify that columns match up
merged_complete = merged_2015.append(merged_2016, ignore_index=True, sort=False)
merged_complete.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,country,Latitude,Longitude,Lower Confidence Interval,Upper Confidence Interval
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,Switzerland,46.818188,8.227512,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,Iceland,64.963051,-19.020835,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,Denmark,56.263920,9.501785,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,Norway,60.472024,8.468946,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,Canada,56.130366,-106.346771,NaN,NaN

In [14]:
merged_complete = merged_complete.append(merged_2017, ignore_index=True, sort=False)
merged_complete = merged_complete.append(merged_2018, ignore_index=True, sort=False)
merged_complete.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,country,Latitude,Longitude,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,Switzerland,46.818188,8.227512,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,Iceland,64.963051,-19.020835,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,Denmark,56.263920,9.501785,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,Norway,60.472024,8.468946,NaN,NaN,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,Canada,56.130366,-106.346771,NaN,NaN,NaN,NaN

In [15]:
merged_complete = merged_complete.sort_values(['Country','Year'])

In [16]:
merged_complete

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,country,Latitude,Longitude,Lower Confidence Interval,Upper Confidence Interval,Whisker.high,Whisker.low
152,Afghanistan,Southern Asia,153,3.575,0.03084,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,1.952100,2015,Afghanistan,33.939110,67.709953,NaN,NaN,NaN,NaN
311,Afghanistan,Southern Asia,154,3.360,NaN,0.382270,0.110370,0.173440,0.164300,0.071120,0.312680,2.145580,2016,Afghanistan,33.939110,67.709953,3.288,3.432,NaN,NaN
455,Afghanistan,NaN,141,3.794,NaN,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871,2.150801,2017,Afghanistan,33.939110,67.709953,NaN,NaN,3.873661,3.714338
612,Afghanistan,NaN,145,3.632,NaN,0.332000,0.537000,0.255000,0.085000,0.036000,0.191000,NaN,2018,Afghanistan,33.939110,67.709953,NaN,NaN,NaN,NaN
94,Albania,Central and Eastern Europe,95,4.959,0.05013,0.878670,0.804340,0.813250,0.357330,0.064130,0.142720,1.898940,2015,Albania,41.153332,20.168331,NaN,NaN,NaN,NaN
266,Albania,Central and Eastern Europe,109,4.655,NaN,0.955300,0.501630,0.730070,0.318660,0.053010,0.168400,1.928160,2016,Albania,41.153332,20.168331,4.546,4.764,NaN,NaN
423,Albania,NaN,109,4.644,NaN,0.996193,0.803685,0.731160,0.381499,0.039864,0.201313,1.490442,2017,Albania,41.153332,20.168331,NaN,NaN,4.752464,4.535536
579,Albania,NaN,112,4.586,NaN,0.916000,0.817000,0.790000,0.419000,0.032000,0.149000,NaN,2018,Albania,41.153332,20.168331,NaN,NaN,NaN,NaN
67,Algeria,Middle East and Northern Africa,68,5.605,0.05099,0.939290,1.077720,0.617660,0.285790,0.173830,0.078220,2.432090,2015,Algeria,28.033886,1.659626,NaN,NaN,NaN,NaN
195,Algeria,Middle East and Northern Africa,38,6.355,NaN,1.052660,0.833090,0.618040,0.210060,0.161570,0.070440,3.409040,2016,Algeria,28.033886,1.659626,6.227,6.483,NaN,NaN
367,Algeria,NaN,53,5.872,NaN,1.091864,1.146217,0.617585,0.233336,0.146096,0.069437,2.567604,2017,Algeria,28.033886,1.659626,NaN,NaN,5.978286,5.765714
551,Algeria,NaN,84,5.295,NaN,0.979000,1.154000,0.687000,0.077000,0.135000,0.055000,NaN,2018,Algeria,28.033886,1.659626,NaN,NaN,NaN,NaN
136,Angola,Sub-Saharan Africa,137,4.033,0.04758,0.757780,0.860400,0.166830,0.103840,0.071220,0.123440,1.949390,2015,Angola,-11.202692,17.873887,NaN,NaN,NaN,NaN
298,Angola,Sub-Saharan Africa,141,3.866,NaN,0.847310,0.663660,0.049910,0.005890,0.084340,0.120710,2.094590,2016,Angola,-11.202692,17.873887,3.753,3.979,NaN,NaN
454,Angola,NaN,140,3.795,NaN,0.858428,1.104412,0.049869,0.000000,0.069720,0.097926,1.614482,2017,Angola,-11.202692,17.873887,NaN,NaN,3.951642,3.638358
609,Angola,NaN,142,3.795,NaN,0.730000,1.125000,0.269000,0.000000,0.061000,0.079000,NaN,2018,Angola,-11.202692,17.873887,NaN,NaN,NaN,NaN
29,Argentina,Latin America and Caribbean,30,6.574,0.04612,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2.836000,2015,Argentina,-38.416097,-63.616672,NaN,NaN,NaN,NaN
183,Argentina,Latin America and Caribbean,26,6.650,NaN,1.151370,1.066120,0.697110,0.422840,0.072960,0.109890,3.129850,2016,Argentina,-38.416097,-63.616672,6.560,6.740,NaN,NaN
338,Argentina,NaN,24,6.599,NaN,1.185295,1.440451,0.695137,0.494519,0.059740,0.109457,2.614005,2017,Argentina,-38.416097,-63.616672,NaN,NaN,6.690085,6.507915
498,Argentina,NaN,29,6.388,NaN,1.073000,1.468000,0.744000,0.570000,0.054000,0.062000,NaN,2018,Argentina,-38.416097,-63.616672,NaN,NaN,NaN,NaN
126,Armenia,Central and Eastern Europe,127,4.350,0.04763,0.768210,0.777110,0.729900,0.198470,0.039000,0.078550,1.758730,2015,Armenia,40.069099,45.038189,NaN,NaN,NaN,NaN
278,Armenia,Central and Eastern Europe,121,4.360,NaN,0.860860,0.624770,0.640830,0.140370,0.036160,0.077930,1.978640,2016,Armenia,40.069099,45.038189,4.266,4.454,NaN,NaN
435,Armenia,NaN,121,4.376,NaN,0.900597,1.007484,0.637524,0.198303,0.026674,0.083488,1.521499,2017,Armenia,40.069099,45.038189,NaN,NaN,4.466735,4.285265
596,Armenia,NaN,129,4.321,NaN,0.816000,0.990000,0.666000,0.260000,0.028000,0.077000,NaN,2018,Armenia,40.069099,45.038189,NaN,NaN,NaN,NaN
9,Australia,Australia and New Zealand,10,7.284,0.04083,1.333580,1.309230,0.931560,0.651240,0.356370,0.435620,2.266460,2015,Australia,-25.274398,133.775136,NaN,NaN,NaN,NaN
166,Australia,Australia and New Zealand,9,7.313,NaN,1.444430,1.104760,0.851200,0.568370,0.323310,0.474070,2.546500,2016,Australia,-25.274398,133.775136,7.241,7.385,NaN,NaN
324,Australia,NaN,10,7.284,NaN,1.484415,1.510042,0.843887,0.601607,0.301184,0.477699,2.065211,2017,Australia,-25.274398,133.775136,NaN,NaN,7.356651,7.211349
479,Australia,NaN,10,7.272,NaN,1.340000,1.573000,0.910000,0.647000,0.302000,0.361000,NaN,2018,Australia,-25.274398,133.775136,NaN,NaN,NaN,NaN
12,Austria,Western Europe,13,7.200,0.03751,1.337230,1.297040,0.890420,0.624330,0.186760,0.330880,2.533200,2015,Austria,47.516231,14.550072,NaN,NaN,NaN,NaN
169,Austria,Western Europe,12,7.119,NaN,1.450380,1.083830,0.805650,0.543550,0.213480,0.328650,2.693430,2016,Austria,47.516231,14.550072,7.045,7.193,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,United States,NaN,14,6.993,NaN,1.546259,1.419921,0.774287,0.505741,0.135639,0.392579,2.218113,2017,United States,37.090240,-95.712891,NaN,NaN,7.074657,6.911343
487,United States,NaN,18,6.886,NaN,1.398000,1.471000,0.819000,0.547000,0.133000,0.291000,NaN,2018,United States,37.090240,-95.712891,NaN,NaN,NaN,NaN
31,Uruguay,Latin America and Caribbean,32,6.485,0.04539,1.061660,1.208900,0.811600,0.603620,0.245580,0.232400,2.321420,2015,Uruguay,-32.522779,-55.765835,NaN,NaN,NaN,NaN
186,Uruguay,Latin America and Caribbean,29,6.545,NaN,1.181570,1.031430,0.721830,0.543880,0.213940,0.180560,2.671390,2016,Uruguay,-32.522779,-55.765835,6.456,6.634,NaN,NaN
342,Uruguay,NaN,28,6.454,NaN,1.217560,1.412228,0.719217,0.579392,0.178062,0.175097,2.172410,2017,Uruguay,-32.522779,-55.765835,NaN,NaN,6.545906,6.362094
500,Uruguay,NaN,31,6.379,NaN,1.093000,1.459000,0.771000,0.625000,0.155000,0.130000,NaN,2018,Uruguay,-32.522779,-55.765835,NaN,NaN,NaN,NaN
43,Uzbekistan,Central and Eastern Europe,44,6.003,0.04361,0.632440,1.340430,0.597720,0.658210,0.308260,0.228370,2.237410,2015,Uzbekistan,41.377491,64.585262,NaN,NaN,NaN,NaN
206,Uzbekistan,Central and Eastern Europe,49,5.987,NaN,0.735910,1.168100,0.501630,0.608480,0.283330,0.343260,2.346380,2016,Uzbekistan,41.377491,64.585262,5.896,6.078,NaN,NaN
361,Uzbekistan,NaN,47,5.971,NaN,0.786441,1.548969,0.498273,0.658249,0.246528,0.415984,1.816914,2017,Uzbekistan,41.377491,64.585262,NaN,NaN,6.065538,5.876463
512,Uzbekistan,NaN,44,6.096,NaN,0.719000,1.584000,0.605000,0.724000,0.259000,0.328000,NaN,2018,Uzbekistan,41.377491,64.585262,NaN,NaN,NaN,NaN
22,Venezuela,Latin America and Caribbean,23,6.810,0.06476,1.044240,1.255960,0.720520,0.429080,0.110690,0.058410,3.191310,2015,Venezuela,6.423750,-66.589730,NaN,NaN,NaN,NaN
201,Venezuela,Latin America and Caribbean,44,6.084,NaN,1.133670,1.033020,0.619040,0.198470,0.083040,0.042500,2.974680,2016,Venezuela,6.423750,-66.589730,5.973,6.195,NaN,NaN
396,Venezuela,NaN,82,5.250,NaN,1.128431,1.431338,0.617144,0.153997,0.064491,0.065020,1.789464,2017,Venezuela,6.423750,-66.589730,NaN,NaN,5.370032,5.129968
569,Venezuela,NaN,102,4.806,NaN,0.996000,1.469000,0.657000,0.133000,0.052000,0.056000,NaN,2018,Venezuela,6.423750,-66.589730,NaN,NaN,NaN,NaN
74,Vietnam,Southeastern Asia,75,5.360,0.03107,0.632160,0.912260,0.746760,0.594440,0.104410,0.168600,2.201730,2015,Vietnam,14.058324,108.277199,NaN,NaN,NaN,NaN
253,Vietnam,Southeastern Asia,96,5.061,NaN,0.740370,0.791170,0.661570,0.559540,0.115560,0.250750,1.941800,2016,Vietnam,14.058324,108.277199,4.991,5.131,NaN,NaN
408,Vietnam,NaN,94,5.074,NaN,0.788548,1.277491,0.652169,0.571056,0.087633,0.234968,1.462319,2017,Vietnam,14.058324,108.277199,NaN,NaN,5.147281,5.000719
562,Vietnam,NaN,95,5.103,NaN,0.715000,1.365000,0.702000,0.618000,0.079000,0.177000,NaN,2018,Vietnam,14.058324,108.277199,NaN,NaN,NaN,NaN
135,Yemen,Middle East and Northern Africa,136,4.077,0.04367,0.546490,0.680930,0.400640,0.355710,0.078540,0.091310,1.923130,2015,Yemen,15.552727,48.516388,NaN,NaN,NaN,NaN
304,Yemen,Middle East and Northern Africa,147,3.724,NaN,0.579390,0.474930,0.310480,0.228700,0.058920,0.098210,1.972950,2016,Yemen,15.552727,48.516388,3.621,3.827,NaN,NaN
460,Yemen,NaN,146,3.593,NaN,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017,Yemen,15.552727,48.516388,NaN,NaN,3.692750,3.493250
619,Yemen,NaN,152,3.355,NaN,0.442000,1.073000,0.343000,0.244000,0.064000,0.083000,NaN,2018,Yemen,15.552727,48.516388,NaN,NaN,NaN,NaN
84,Zambia,Sub-Saharan Africa,85,5.129,0.06988,0.470380,0.916120,0.299240,0.488270,0.124680,0.195910,2.634300,2015,Zambia,-13.133897,27.849332,NaN,NaN,NaN,NaN
263,Zambia,Sub-Saharan Africa,106,4.795,NaN,0.612020,0.637600,0.235730,0.426620,0.114790,0.178660,2.589910,2016,Zambia,-13.133897,27.849332,4.645,4.945,NaN,NaN
430,Zambia,NaN,116,4.514,NaN,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,1.826705,2017,Zambia,-13.133897,27.849332,NaN,NaN,4.644106,4.383894
592,Zambia,NaN,125,4.377,NaN,0.562000,1.047000,0.295000,0.503000,0.082000,0.221000,NaN,2018,Zambia,-13.133897,27.849332,NaN,NaN,NaN,NaN
114,Zimbabwe,Sub-Saharan Africa,115,4.610,0.04290,0.271000,1.032760,0.334750,0.258610,0.080790,0.189870,2.441910,2015,Zimbabwe,-19.015438,29.154857,NaN,NaN,NaN,NaN
288,Zimbabwe,Sub-Saharan Africa,131,4.193,NaN,0.350410,0.714780,0.159500,0.254290,0.085820,0.185030,2.442700,2016,Zimbabwe,-19.015438,29.154857,4.101,4.285,NaN,NaN
452,Zimbabwe,NaN,138,3.875,NaN,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017,Zimbabwe,-19.015438,29.154857,NaN,NaN,3.978700,3.771300
611,Zimbabwe,NaN,144,3.692,NaN,0.357000,1.094000,0.248000,0.406000,0.099000,0.132000,NaN,2018,Zimbabwe,-19.015438,29.154857,NaN,NaN,NaN,NaN

In [17]:
# Remove columns: country, Region, Standard Error, Lower Confidence Interval, Upper Confidence Interval, Whisker.high, Whisker.low
cleaned_merged_complete = merged_complete.drop(columns=['Dystopia Residual','country', 'Region', 'Standard Error', 'Lower Confidence Interval', 'Upper Confidence Interval', 'Whisker.high', 'Whisker.low'])
cleaned_merged_complete

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Year,Latitude,Longitude
152,Afghanistan,153,3.575,0.319820,0.302850,0.303350,0.234140,0.097190,0.365100,2015,33.939110,67.709953
311,Afghanistan,154,3.360,0.382270,0.110370,0.173440,0.164300,0.071120,0.312680,2016,33.939110,67.709953
455,Afghanistan,141,3.794,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871,2017,33.939110,67.709953
612,Afghanistan,145,3.632,0.332000,0.537000,0.255000,0.085000,0.036000,0.191000,2018,33.939110,67.709953
94,Albania,95,4.959,0.878670,0.804340,0.813250,0.357330,0.064130,0.142720,2015,41.153332,20.168331
266,Albania,109,4.655,0.955300,0.501630,0.730070,0.318660,0.053010,0.168400,2016,41.153332,20.168331
423,Albania,109,4.644,0.996193,0.803685,0.731160,0.381499,0.039864,0.201313,2017,41.153332,20.168331
579,Albania,112,4.586,0.916000,0.817000,0.790000,0.419000,0.032000,0.149000,2018,41.153332,20.168331
67,Algeria,68,5.605,0.939290,1.077720,0.617660,0.285790,0.173830,0.078220,2015,28.033886,1.659626
195,Algeria,38,6.355,1.052660,0.833090,0.618040,0.210060,0.161570,0.070440,2016,28.033886,1.659626
367,Algeria,53,5.872,1.091864,1.146217,0.617585,0.233336,0.146096,0.069437,2017,28.033886,1.659626
551,Algeria,84,5.295,0.979000,1.154000,0.687000,0.077000,0.135000,0.055000,2018,28.033886,1.659626
136,Angola,137,4.033,0.757780,0.860400,0.166830,0.103840,0.071220,0.123440,2015,-11.202692,17.873887
298,Angola,141,3.866,0.847310,0.663660,0.049910,0.005890,0.084340,0.120710,2016,-11.202692,17.873887
454,Angola,140,3.795,0.858428,1.104412,0.049869,0.000000,0.069720,0.097926,2017,-11.202692,17.873887
609,Angola,142,3.795,0.730000,1.125000,0.269000,0.000000,0.061000,0.079000,2018,-11.202692,17.873887
29,Argentina,30,6.574,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2015,-38.416097,-63.616672
183,Argentina,26,6.650,1.151370,1.066120,0.697110,0.422840,0.072960,0.109890,2016,-38.416097,-63.616672
338,Argentina,24,6.599,1.185295,1.440451,0.695137,0.494519,0.059740,0.109457,2017,-38.416097,-63.616672
498,Argentina,29,6.388,1.073000,1.468000,0.744000,0.570000,0.054000,0.062000,2018,-38.416097,-63.616672
126,Armenia,127,4.350,0.768210,0.777110,0.729900,0.198470,0.039000,0.078550,2015,40.069099,45.038189
278,Armenia,121,4.360,0.860860,0.624770,0.640830,0.140370,0.036160,0.077930,2016,40.069099,45.038189
435,Armenia,121,4.376,0.900597,1.007484,0.637524,0.198303,0.026674,0.083488,2017,40.069099,45.038189
596,Armenia,129,4.321,0.816000,0.990000,0.666000,0.260000,0.028000,0.077000,2018,40.069099,45.038189
9,Australia,10,7.284,1.333580,1.309230,0.931560,0.651240,0.356370,0.435620,2015,-25.274398,133.775136
166,Australia,9,7.313,1.444430,1.104760,0.851200,0.568370,0.323310,0.474070,2016,-25.274398,133.775136
324,Australia,10,7.284,1.484415,1.510042,0.843887,0.601607,0.301184,0.477699,2017,-25.274398,133.775136
479,Australia,10,7.272,1.340000,1.573000,0.910000,0.647000,0.302000,0.361000,2018,-25.274398,133.775136
12,Austria,13,7.200,1.337230,1.297040,0.890420,0.624330,0.186760,0.330880,2015,47.516231,14.550072
169,Austria,12,7.119,1.450380,1.083830,0.805650,0.543550,0.213480,0.328650,2016,47.516231,14.550072
...,...,...,...,...,...,...,...,...,...,...,...,...
328,United States,14,6.993,1.546259,1.419921,0.774287,0.505741,0.135639,0.392579,2017,37.090240,-95.712891
487,United States,18,6.886,1.398000,1.471000,0.819000,0.547000,0.133000,0.291000,2018,37.090240,-95.712891
31,Uruguay,32,6.485,1.061660,1.208900,0.811600,0.603620,0.245580,0.232400,2015,-32.522779,-55.765835
186,Uruguay,29,6.545,1.181570,1.031430,0.721830,0.543880,0.213940,0.180560,2016,-32.522779,-55.765835
342,Uruguay,28,6.454,1.217560,1.412228,0.719217,0.579392,0.178062,0.175097,2017,-32.522779,-55.765835
500,Uruguay,31,6.379,1.093000,1.459000,0.771000,0.625000,0.155000,0.130000,2018,-32.522779,-55.765835
43,Uzbekistan,44,6.003,0.632440,1.340430,0.597720,0.658210,0.308260,0.228370,2015,41.377491,64.585262
206,Uzbekistan,49,5.987,0.735910,1.168100,0.501630,0.608480,0.283330,0.343260,2016,41.377491,64.585262
361,Uzbekistan,47,5.971,0.786441,1.548969,0.498273,0.658249,0.246528,0.415984,2017,41.377491,64.585262
512,Uzbekistan,44,6.096,0.719000,1.584000,0.605000,0.724000,0.259000,0.328000,2018,41.377491,64.585262
22,Venezuela,23,6.810,1.044240,1.255960,0.720520,0.429080,0.110690,0.058410,2015,6.423750,-66.589730
201,Venezuela,44,6.084,1.133670,1.033020,0.619040,0.198470,0.083040,0.042500,2016,6.423750,-66.589730
396,Venezuela,82,5.250,1.128431,1.431338,0.617144,0.153997,0.064491,0.065020,2017,6.423750,-66.589730
569,Venezuela,102,4.806,0.996000,1.469000,0.657000,0.133000,0.052000,0.056000,2018,6.423750,-66.589730
74,Vietnam,75,5.360,0.632160,0.912260,0.746760,0.594440,0.104410,0.168600,2015,14.058324,108.277199
253,Vietnam,96,5.061,0.740370,0.791170,0.661570,0.559540,0.115560,0.250750,2016,14.058324,108.277199
408,Vietnam,94,5.074,0.788548,1.277491,0.652169,0.571056,0.087633,0.234968,2017,14.058324,108.277199
562,Vietnam,95,5.103,0.715000,1.365000,0.702000,0.618000,0.079000,0.177000,2018,14.058324,108.277199
135,Yemen,136,4.077,0.546490,0.680930,0.400640,0.355710,0.078540,0.091310,2015,15.552727,48.516388
304,Yemen,147,3.724,0.579390,0.474930,0.310480,0.228700,0.058920,0.098210,2016,15.552727,48.516388
460,Yemen,146,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,2017,15.552727,48.516388
619,Yemen,152,3.355,0.442000,1.073000,0.343000,0.244000,0.064000,0.083000,2018,15.552727,48.516388
84,Zambia,85,5.129,0.470380,0.916120,0.299240,0.488270,0.124680,0.195910,2015,-13.133897,27.849332
263,Zambia,106,4.795,0.612020,0.637600,0.235730,0.426620,0.114790,0.178660,2016,-13.133897,27.849332
430,Zambia,116,4.514,0.636407,1.003187,0.257836,0.461603,0.078214,0.249580,2017,-13.133897,27.849332
592,Zambia,125,4.377,0.562000,1.047000,0.295000,0.503000,0.082000,0.221000,2018,-13.133897,27.849332
114,Zimbabwe,115,4.610,0.271000,1.032760,0.334750,0.258610,0.080790,0.189870,2015,-19.015438,29.154857
288,Zimbabwe,131,4.193,0.350410,0.714780,0.159500,0.254290,0.085820,0.185030,2016,-19.015438,29.154857
452,Zimbabwe,138,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,2017,-19.015438,29.154857
611,Zimbabwe,144,3.692,0.357000,1.094000,0.248000,0.406000,0.099000,0.132000,2018,-19.015438,29.154857

In [19]:
cleaned_merged_complete["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain',
       'Bangladesh', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo (Brazzaville)', 'Congo (Kinshasa)',
       'Costa Rica', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark',
       'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Estonia', 'Ethiopia', 'Finland', 'France', 'Gabon',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea',
       'Haiti', 'Honduras', 'Hong Kong', 'Hong Kong S.A.R., China',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
       'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Lithuania', 'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi',
       'Malaysia', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Cyprus', 'Norway', 'Oman',
       'Pakistan', 'Palestinian Territories', 'Panama', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico',
       'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Somalia', 'Somaliland Region', 'Somaliland region',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria',
       'Taiwan', 'Taiwan Province of China', 'Tajikistan', 'Tanzania',
       'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)